### ISSUE TITLE
Support for custom/multiple prefix keys?

### ISSUE THREAD

**Issue by Just-Insane** [MunifTanjim/tmux-suspend#5]
I am trying to use this plugin, however in my setup, I use `C-a` as prefix2 (so both `C-b` and `C-a` work as prefix keys), however, this plugin only suspends the outer session when attempting to use `C-b`.

Is it possible to support custom or multiple prefix keys?

**Comment by Just-Insane** [comment]
I resolved this by unsetting `C-b`, since I don't use it, and changed `C-a` to `prefix` instead of `prefix2`

**Comment by MunifTanjim** [comment]
Interesting. I don't use `prefix2` myself. But I think you can make it work with `@suspend_suspended_options`.

`prefix2` is just an option like all other options. So if you set `@suspend_suspended_options` like this:

```
set -g @suspend_suspended_options " \
  prefix2::none, \
"
```

What `tmux-suspend` will do is:
- when you suspend your local tmux session, `prefix2` will be set to none.
- when you resume your local tmux session, `prefix2` will be reverted back to original value.

You can check the details for it here: https://github.com/MunifTanjim/tmux-suspend/blob/f7d59c04/README.md#suspend_suspended_options
