### ISSUE TITLE
how to configure status format option

### ISSUE THREAD

**Issue by amigthea** [MunifTanjim/tmux-suspend#6]
I can't figure out how to configure options like status-right in the @suspend_suspended_options configuration.

```
set -g @suspend_suspended_options " \
  @mode_indicator_custom_prompt:: ---- , \
  @mode_indicator_custom_mode_style::bg=brightblack\\,fg=black, \
  status-right::#{tmux_mode_indicator} [fg=colour15,bg=colour136]#{?window_zoomed_flag, ZOOM ,}#[default] [fg=colour136]#(whoami)#[default]@#H | [fg=colour136]%h %d %H:%M:%S#[default] #{online_status}, \
  status-style::bg=brightblack\\,fg=colour15, \
  window-status-current-style::bg=colour245\\,fg=colour15, \
"
```

This code fails at the status-right line

**Comment by MunifTanjim** [comment]
Inside `@suspend_suspended_options`, you'll need to escape some characters, e.g.:

- `#` as `##`
- `,` as `\\,`

You'll need to set `status-right` as global. So it would look something like this (not tested):

```
  status-right:g:##{tmux_mode_indicator} [fg=colour15\\,bg=colour136]##{?window_zoomed_flag\\, ZOOM \\,}#[default] [fg=colour136]##(whoami)#[default]@##H | [fg=colour136]%h %d %H:%M:%S#[default] ##{online_status}, \
```

Also `#{tmux_mode_indicator}` is expanded on tmux startup, so it won't be expanded again if you set it later. If you want to do that you'll need to run the [`tmux-mode-indicator/mode_indicator.tmux`](https://github.com/MunifTanjim/tmux-mode-indicator/blob/11520829210a34dc9c7e5be9dead152eaf3a4423/mode_indicator.tmux) script. So you can do something like:

```
set -g @suspend_on_suspend_command "tmux run-shell ~/.tmux/plugins/tmux-mode-indicator/mode_indicator.tmux"
```

I'm guessing you'll also need to do it for `#{online_status}`, so

```
set -g @suspend_on_suspend_command "tmux run-shell ~/.tmux/plugins/tmux-mode-indicator/mode_indicator.tmux && tmux run-shell ~/.tmux/plugins/tmux-online-status/online_status.tmux"
```

**Comment by amigthea** [comment]
thank you @MunifTanjim for all the suggestion, really appreciated!

Working on those I've come up with a working solution:
```
  status-right:g:##{tmux_mode_indicator} ##{?window_zoomed_flag\\, ZOOM \\,} ##(whoami)@##H | %h %d %H:%M:%S ##{online_status}, \
```
but I've stripped off colour sections because they're not working, it's like they're escaped and displayed as a string like this:
```
#[fg=colour15\\,bg=colour136]
```

**Comment by MunifTanjim** [comment]
> it's like they're escaped and displayed as a string like this

Probably because of some escaping issue, I'm not entirely sure about how tmux interprets the sequence.

What you can do is, run this command when in suspended state:

```sh
tmux show-options -g status-right
```

to see the actual value that was set.

**Comment by MunifTanjim** [comment]
This seems to be working:

```
  status-right:g:##{tmux_mode_indicator} #[fg=colour15\\,bg=colour136]##{?window_zoomed_flag\\, ZOOM \\,}#[default] #[fg=colour136]##(whoami)#[default]@##H | #[fg=colour136]%h %d %H:%M:%S#[default] ##{online_status}, \
```

**Comment by amigthea** [comment]
Indeed it is! thank you so much for the time you dedicated me, have a nice day!
