### ISSUE TITLE
vi mode not work(cant copy) in suspend state

### ISSUE THREAD

**Issue by kugarocks** [MunifTanjim/tmux-suspend#8]
I log into a server remotely from tmux, then start another tmux session. When I am in suspend state and enter vi mode, after selecting the text, I can't copy the content when I press the Enter key. Thanks for any help.

**Comment by MunifTanjim** [comment]
When you say "I can't copy the content when I press the Enter key", what do you mean?

Are you expecting the text from your remote tmux session to be copied in your system clipboard?

**Comment by kugarocks** [comment]
> When you say "I can't copy the content when I press the Enter key", what do you mean?
> 
> Are you expecting the text from your remote tmux session to be copied in your system clipboard?

Yes, the clipboard is empty.

![suspend-vi-mode](https://github.com/user-attachments/assets/b58cf718-5bea-478c-9af1-8cf41ce3cac2)

**Comment by MunifTanjim** [comment]
Remote tmux doesn't have access to your operating system's clipboard. This will behave the same with or without `tmux-suspend` plugin.

**Comment by kugarocks** [comment]
> Remote tmux doesn't have access to your operating system's clipboard. This will behave the same with or without `tmux-suspend` plugin.

But if I not use tmux inside tmux, it work.

**Comment by kugarocks** [comment]
> Remote tmux doesn't have access to your operating system's clipboard. This will behave the same with or without `tmux-suspend` plugin.

Is there any way to do this? If not, use tmux inside a tmux will always lack of some function.

**Comment by MunifTanjim** [comment]
You can probably use OSC52 for this. But it's really outside the scope of this plugin. It's better if you ask this in a Tmux community, maybe Reddit or GitHub repo.
